#!/usr/bin/env sh

usage() {
    echo "Track a remote branch"
    echo "usage: <remote> [<remote-branch>]"
    echo
}

version() {
    echo "git-extensions git plugin v0.0.1"
    echo
}

main() {
    if [ "$#" -lt 1 ]; then
        usage; exit 1
    fi

    local subcommand="$1";

    case $subcommand in
        "-h"|"--help")
            usage; exit 0
            ;;
        "-v"|"--version")
            version; exit 0
            ;;
    esac

    SUBDIRECTORY_OK=Yes
    OPTIONS_SPEC=

    . "`git --exec-path`/git-sh-setup"

    branch=`git symbolic-ref -q HEAD | sed "s!refs/heads/!!"`

    if [ "$branch" = "" ]
    then
      die "Make sure you're on a branch."
    fi

    remote=$1

    if [ "$1" = "" ]
    then
      die "You need to specify a remote."
    fi

    if [ "$2" = "" ]
    then
      merge=$branch
    else
      merge=$2
    fi

    git config branch.$branch.remote $remote
    git config branch.$branch.merge refs/heads/$merge

    echo "Tracking $remote/$merge"

    exit 0
}

main "$@"